name: Cross-compiler-toolchain 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 00 16 * * *
  watch:
    types: [started]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
 Cross-compiler-toolchain :
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@v4
      with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-android: 'true'
    - name: Echo 
      run: |
            ls
    - name: Checkout
      uses: actions/checkout@v2
    - name: Echo Free space
      run: |
          echo "Free space:"
          df -h
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 
    - name: Prepare Env
      run: |
        sudo apt-get update
        sudo apt-get install libncurses5-dev gperf bison  flex texinfo help2man gawk libtool libtool-bin automake
        sudo apt install build-essential
        sudo apt install python-dev-is-python3
    - name: Build 
      run: |
        git clone https://github.com/crosstool-ng/crosstool-ng.git
        cd crosstool-ng
        ./bootstrap
        ./configure
        make
        sudo make install
    - name: env
      run: |
        unset LD_LIBRARY_PATH
        mkdir tools
        sudo mkdir /home/src
        cd tools
        ct-ng aarch64-unknown-linux-gnu
        ct-ng build V=2
    - name: ZIP
      run: |
         sudo tar –czf aarch64-unknown-linux-gnu.tar.gz /home/x-tools/aarch64-unknown-linux-gnu
    - name: Release Engine
      uses: ncipollo/release-action@v1
      with:
        artifacts: "*.tar.gz"
        tag: aarch64-unknown-linux-gnu
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
